name: test
on: [push]
permissions:
  contents: read

jobs:

  build:
    name: Test and Build
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:

    - name: Set up Go 1.26.3
      uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
      with:
        go-version: 1.26.3
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: cache
      uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Get dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: go mod download

    - name: Test
      run: make test

    - name: Build
      run: make build
