name: test
on: [push]
permissions:
  contents: read

jobs:

  build:
    name: Test and Build
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:

    - name: Set up Go 1.26.3
      uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
      with:
        go-version: 1.26.3
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

    - name: cache
      uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Get dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: go mod download

    - name: Test
      run: make test-all

    - name: Build (arm64)
      run: make build

    - name: Build (x86_64)
      run: make build-x86_64
